/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.11.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *groupBox;
    QPushButton *bnt_listPorts;
    QComboBox *combo_ports;
    QPushButton *bnt_connect;
    QPushButton *bnt_desconnect;
    QLabel *label_status;
    QGroupBox *groupBox_2;
    QPushButton *bnt_format;
    QPushButton *bnt_readData;
    QPushButton *bnt_writeData;
    QTabWidget *tabWidget;
    QWidget *tab;
    QLineEdit *lineMessage;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_11;
    QComboBox *combo_symbolTable;
    QLabel *label_12;
    QLabel *label_2;
    QLineEdit *lineSymbol;
    QLabel *label_23;
    QLineEdit *lineSSID;
    QComboBox *combo_path2;
    QComboBox *combo_path1;
    QLabel *label;
    QLineEdit *lineCall;
    QWidget *Smart;
    QGroupBox *groupBox_9;
    QComboBox *combo_delay1;
    QComboBox *combo_delay2;
    QComboBox *combo_delay3;
    QComboBox *combo_speed1;
    QComboBox *combo_speed2;
    QComboBox *combo_speed3;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QComboBox *combo_delay4;
    QLabel *label_40;
    QGroupBox *groupBox_8;
    QComboBox *combo_cspeed;
    QComboBox *combo_cangle;
    QLabel *label_25;
    QLabel *label_24;
    QComboBox *combo_ctime;
    QLabel *label_26;
    QCheckBox *checkBox_course;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QWidget *Radio;
    QGroupBox *groupBox_7;
    QLabel *label_17;
    QLineEdit *line_txbeep;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *line_rxbeep;
    QLabel *label_20;
    QLabel *label_21;
    QLineEdit *line_repbeep;
    QLabel *label_22;
    QGroupBox *groupBox_6;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *line_txpreamble;
    QLineEdit *line_txtail;
    QLabel *label_15;
    QLabel *label_16;
    QWidget *Beacon;
    QGroupBox *groupBox_4;
    QLineEdit *line_fixlat;
    QLineEdit *line_fixlon;
    QLabel *label_9;
    QLabel *label_10;
    QComboBox *combo_South;
    QComboBox *combo_West;
    QCheckBox *checkBox_beacon;
    QComboBox *combo_fixdelay;
    QLabel *label_39;
    QGroupBox *groupBox_5;
    QLabel *label_3;
    QLabel *label_4;
    QComboBox *comboHeight;
    QLabel *label_5;
    QComboBox *comboGain;
    QLabel *label_6;
    QComboBox *comboDirection;
    QComboBox *comboPower;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(372, 343);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        QIcon icon;
        icon.addFile(QStringLiteral(":/icons/icons/if_Setting_37062.png"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 10, 351, 71));
        bnt_listPorts = new QPushButton(groupBox);
        bnt_listPorts->setObjectName(QStringLiteral("bnt_listPorts"));
        bnt_listPorts->setGeometry(QRect(10, 30, 91, 21));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/icons/icons/if_system-search_118797.png"), QSize(), QIcon::Normal, QIcon::Off);
        bnt_listPorts->setIcon(icon1);
        combo_ports = new QComboBox(groupBox);
        combo_ports->setObjectName(QStringLiteral("combo_ports"));
        combo_ports->setGeometry(QRect(110, 30, 141, 21));
        bnt_connect = new QPushButton(groupBox);
        bnt_connect->setObjectName(QStringLiteral("bnt_connect"));
        bnt_connect->setGeometry(QRect(260, 12, 81, 21));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/icons/icons/if_go-next_118773.png"), QSize(), QIcon::Normal, QIcon::Off);
        bnt_connect->setIcon(icon2);
        bnt_desconnect = new QPushButton(groupBox);
        bnt_desconnect->setObjectName(QStringLiteral("bnt_desconnect"));
        bnt_desconnect->setEnabled(false);
        bnt_desconnect->setGeometry(QRect(260, 40, 81, 21));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/icons/icons/if_process-stop_118794.png"), QSize(), QIcon::Normal, QIcon::Off);
        bnt_desconnect->setIcon(icon3);
        label_status = new QLabel(groupBox);
        label_status->setObjectName(QStringLiteral("label_status"));
        label_status->setEnabled(true);
        label_status->setGeometry(QRect(150, 50, 81, 16));
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 80, 351, 51));
        bnt_format = new QPushButton(groupBox_2);
        bnt_format->setObjectName(QStringLiteral("bnt_format"));
        bnt_format->setEnabled(false);
        bnt_format->setGeometry(QRect(10, 20, 101, 23));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/icons/icons/if_dialog-warning_118940.png"), QSize(), QIcon::Normal, QIcon::Off);
        bnt_format->setIcon(icon4);
        bnt_readData = new QPushButton(groupBox_2);
        bnt_readData->setObjectName(QStringLiteral("bnt_readData"));
        bnt_readData->setEnabled(false);
        bnt_readData->setGeometry(QRect(130, 20, 101, 23));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/icons/icons/if_blue_arrow_up_36873.png"), QSize(), QIcon::Normal, QIcon::Off);
        bnt_readData->setIcon(icon5);
        bnt_writeData = new QPushButton(groupBox_2);
        bnt_writeData->setObjectName(QStringLiteral("bnt_writeData"));
        bnt_writeData->setEnabled(false);
        bnt_writeData->setGeometry(QRect(250, 20, 91, 23));
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/icons/icons/if_misc_28_10769.png"), QSize(), QIcon::Normal, QIcon::Off);
        bnt_writeData->setIcon(icon6);
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 140, 351, 191));
        tabWidget->setIconSize(QSize(20, 20));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        lineMessage = new QLineEdit(tab);
        lineMessage->setObjectName(QStringLiteral("lineMessage"));
        lineMessage->setGeometry(QRect(100, 118, 181, 21));
        lineMessage->setMaxLength(25);
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(50, 40, 34, 16));
        label_8 = new QLabel(tab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(150, 39, 61, 16));
        label_11 = new QLabel(tab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(50, 80, 36, 16));
        combo_symbolTable = new QComboBox(tab);
        combo_symbolTable->addItem(QString());
        combo_symbolTable->addItem(QString());
        combo_symbolTable->setObjectName(QStringLiteral("combo_symbolTable"));
        combo_symbolTable->setGeometry(QRect(219, 39, 71, 20));
        label_12 = new QLabel(tab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(179, 80, 36, 16));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(190, 9, 31, 20));
        lineSymbol = new QLineEdit(tab);
        lineSymbol->setObjectName(QStringLiteral("lineSymbol"));
        lineSymbol->setGeometry(QRect(90, 40, 51, 20));
        label_23 = new QLabel(tab);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(50, 119, 47, 16));
        lineSSID = new QLineEdit(tab);
        lineSSID->setObjectName(QStringLiteral("lineSSID"));
        lineSSID->setGeometry(QRect(220, 9, 21, 20));
        combo_path2 = new QComboBox(tab);
        combo_path2->addItem(QString());
        combo_path2->addItem(QString());
        combo_path2->setObjectName(QStringLiteral("combo_path2"));
        combo_path2->setGeometry(QRect(220, 80, 69, 20));
        combo_path1 = new QComboBox(tab);
        combo_path1->addItem(QString());
        combo_path1->addItem(QString());
        combo_path1->setObjectName(QStringLiteral("combo_path1"));
        combo_path1->setGeometry(QRect(92, 80, 69, 20));
        label = new QLabel(tab);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(50, 10, 41, 21));
        sizePolicy.setHeightForWidth(label->sizePolicy().hasHeightForWidth());
        label->setSizePolicy(sizePolicy);
        lineCall = new QLineEdit(tab);
        lineCall->setObjectName(QStringLiteral("lineCall"));
        lineCall->setGeometry(QRect(90, 10, 71, 21));
        sizePolicy.setHeightForWidth(lineCall->sizePolicy().hasHeightForWidth());
        lineCall->setSizePolicy(sizePolicy);
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/icons/icons/if_Config-Tools_49236.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget->addTab(tab, icon7, QString());
        Smart = new QWidget();
        Smart->setObjectName(QStringLiteral("Smart"));
        groupBox_9 = new QGroupBox(Smart);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(10, 10, 171, 141));
        combo_delay1 = new QComboBox(groupBox_9);
        combo_delay1->addItem(QString());
        combo_delay1->addItem(QString());
        combo_delay1->addItem(QString());
        combo_delay1->addItem(QString());
        combo_delay1->addItem(QString());
        combo_delay1->addItem(QString());
        combo_delay1->addItem(QString());
        combo_delay1->setObjectName(QStringLiteral("combo_delay1"));
        combo_delay1->setGeometry(QRect(110, 20, 41, 16));
        combo_delay1->setEditable(true);
        combo_delay2 = new QComboBox(groupBox_9);
        combo_delay2->addItem(QString());
        combo_delay2->addItem(QString());
        combo_delay2->addItem(QString());
        combo_delay2->addItem(QString());
        combo_delay2->addItem(QString());
        combo_delay2->addItem(QString());
        combo_delay2->setObjectName(QStringLiteral("combo_delay2"));
        combo_delay2->setGeometry(QRect(110, 50, 41, 16));
        combo_delay2->setEditable(true);
        combo_delay3 = new QComboBox(groupBox_9);
        combo_delay3->addItem(QString());
        combo_delay3->addItem(QString());
        combo_delay3->addItem(QString());
        combo_delay3->addItem(QString());
        combo_delay3->addItem(QString());
        combo_delay3->addItem(QString());
        combo_delay3->addItem(QString());
        combo_delay3->addItem(QString());
        combo_delay3->addItem(QString());
        combo_delay3->setObjectName(QStringLiteral("combo_delay3"));
        combo_delay3->setGeometry(QRect(110, 80, 41, 16));
        combo_delay3->setEditable(true);
        combo_speed1 = new QComboBox(groupBox_9);
        combo_speed1->addItem(QString());
        combo_speed1->addItem(QString());
        combo_speed1->addItem(QString());
        combo_speed1->setObjectName(QStringLiteral("combo_speed1"));
        combo_speed1->setGeometry(QRect(20, 30, 41, 16));
        combo_speed1->setEditable(true);
        combo_speed2 = new QComboBox(groupBox_9);
        combo_speed2->addItem(QString());
        combo_speed2->addItem(QString());
        combo_speed2->addItem(QString());
        combo_speed2->addItem(QString());
        combo_speed2->setObjectName(QStringLiteral("combo_speed2"));
        combo_speed2->setGeometry(QRect(20, 65, 38, 20));
        combo_speed2->setEditable(true);
        combo_speed3 = new QComboBox(groupBox_9);
        combo_speed3->addItem(QString());
        combo_speed3->addItem(QString());
        combo_speed3->addItem(QString());
        combo_speed3->setObjectName(QStringLiteral("combo_speed3"));
        combo_speed3->setGeometry(QRect(20, 100, 41, 16));
        combo_speed3->setEditable(true);
        label_27 = new QLabel(groupBox_9);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 30, 20, 16));
        label_28 = new QLabel(groupBox_9);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 65, 21, 16));
        label_29 = new QLabel(groupBox_9);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(10, 100, 20, 16));
        label_33 = new QLabel(groupBox_9);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(60, 30, 31, 16));
        label_34 = new QLabel(groupBox_9);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(60, 65, 31, 16));
        label_35 = new QLabel(groupBox_9);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(60, 100, 31, 16));
        label_36 = new QLabel(groupBox_9);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(150, 20, 21, 16));
        label_37 = new QLabel(groupBox_9);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(150, 50, 21, 16));
        label_38 = new QLabel(groupBox_9);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(150, 80, 21, 16));
        combo_delay4 = new QComboBox(groupBox_9);
        combo_delay4->addItem(QString());
        combo_delay4->addItem(QString());
        combo_delay4->addItem(QString());
        combo_delay4->addItem(QString());
        combo_delay4->addItem(QString());
        combo_delay4->addItem(QString());
        combo_delay4->addItem(QString());
        combo_delay4->addItem(QString());
        combo_delay4->addItem(QString());
        combo_delay4->setObjectName(QStringLiteral("combo_delay4"));
        combo_delay4->setGeometry(QRect(110, 110, 41, 16));
        combo_delay4->setEditable(true);
        label_40 = new QLabel(groupBox_9);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(150, 110, 21, 16));
        groupBox_8 = new QGroupBox(Smart);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(190, 10, 151, 141));
        combo_cspeed = new QComboBox(groupBox_8);
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->addItem(QString());
        combo_cspeed->setObjectName(QStringLiteral("combo_cspeed"));
        combo_cspeed->setGeometry(QRect(70, 110, 41, 22));
        combo_cspeed->setEditable(true);
        combo_cangle = new QComboBox(groupBox_8);
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->addItem(QString());
        combo_cangle->setObjectName(QStringLiteral("combo_cangle"));
        combo_cangle->setGeometry(QRect(70, 50, 41, 22));
        combo_cangle->setEditable(true);
        label_25 = new QLabel(groupBox_8);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(20, 80, 41, 20));
        label_24 = new QLabel(groupBox_8);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(16, 50, 51, 20));
        combo_ctime = new QComboBox(groupBox_8);
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->addItem(QString());
        combo_ctime->setObjectName(QStringLiteral("combo_ctime"));
        combo_ctime->setGeometry(QRect(70, 80, 41, 20));
        combo_ctime->setEditable(true);
        label_26 = new QLabel(groupBox_8);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 110, 51, 20));
        checkBox_course = new QCheckBox(groupBox_8);
        checkBox_course->setObjectName(QStringLiteral("checkBox_course"));
        checkBox_course->setGeometry(QRect(10, 20, 70, 17));
        label_30 = new QLabel(groupBox_8);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(110, 50, 31, 20));
        label_31 = new QLabel(groupBox_8);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(110, 80, 31, 20));
        label_32 = new QLabel(groupBox_8);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(110, 110, 31, 20));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/icons/icons/if_compass_51901.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget->addTab(Smart, icon8, QString());
        Radio = new QWidget();
        Radio->setObjectName(QStringLiteral("Radio"));
        groupBox_7 = new QGroupBox(Radio);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setEnabled(true);
        groupBox_7->setGeometry(QRect(160, 20, 171, 111));
        label_17 = new QLabel(groupBox_7);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(140, 20, 21, 16));
        line_txbeep = new QLineEdit(groupBox_7);
        line_txbeep->setObjectName(QStringLiteral("line_txbeep"));
        line_txbeep->setGeometry(QRect(90, 20, 51, 20));
        label_18 = new QLabel(groupBox_7);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(20, 20, 71, 16));
        label_19 = new QLabel(groupBox_7);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(140, 50, 21, 16));
        line_rxbeep = new QLineEdit(groupBox_7);
        line_rxbeep->setObjectName(QStringLiteral("line_rxbeep"));
        line_rxbeep->setGeometry(QRect(90, 50, 51, 20));
        label_20 = new QLabel(groupBox_7);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(20, 50, 71, 16));
        label_21 = new QLabel(groupBox_7);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(140, 80, 21, 16));
        line_repbeep = new QLineEdit(groupBox_7);
        line_repbeep->setObjectName(QStringLiteral("line_repbeep"));
        line_repbeep->setGeometry(QRect(90, 80, 51, 20));
        label_22 = new QLabel(groupBox_7);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 80, 81, 20));
        groupBox_6 = new QGroupBox(Radio);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(0, 20, 151, 80));
        label_13 = new QLabel(groupBox_6);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 20, 71, 16));
        label_14 = new QLabel(groupBox_6);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 50, 71, 16));
        line_txpreamble = new QLineEdit(groupBox_6);
        line_txpreamble->setObjectName(QStringLiteral("line_txpreamble"));
        line_txpreamble->setGeometry(QRect(80, 20, 31, 20));
        line_txtail = new QLineEdit(groupBox_6);
        line_txtail->setObjectName(QStringLiteral("line_txtail"));
        line_txtail->setGeometry(QRect(80, 50, 31, 20));
        label_15 = new QLabel(groupBox_6);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(120, 20, 21, 16));
        label_16 = new QLabel(groupBox_6);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(120, 50, 21, 16));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/icons/icons/if_panneau de configuration old school_37762.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget->addTab(Radio, icon9, QString());
        Beacon = new QWidget();
        Beacon->setObjectName(QStringLiteral("Beacon"));
        groupBox_4 = new QGroupBox(Beacon);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 10, 191, 121));
        line_fixlat = new QLineEdit(groupBox_4);
        line_fixlat->setObjectName(QStringLiteral("line_fixlat"));
        line_fixlat->setEnabled(false);
        line_fixlat->setGeometry(QRect(60, 60, 61, 20));
        line_fixlat->setCursorPosition(7);
        line_fixlon = new QLineEdit(groupBox_4);
        line_fixlon->setObjectName(QStringLiteral("line_fixlon"));
        line_fixlon->setEnabled(false);
        line_fixlon->setGeometry(QRect(60, 90, 61, 20));
        line_fixlon->setCursorPosition(8);
        label_9 = new QLabel(groupBox_4);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setEnabled(false);
        label_9->setGeometry(QRect(10, 60, 47, 16));
        label_10 = new QLabel(groupBox_4);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setEnabled(false);
        label_10->setGeometry(QRect(6, 90, 51, 20));
        combo_South = new QComboBox(groupBox_4);
        combo_South->addItem(QString());
        combo_South->addItem(QString());
        combo_South->setObjectName(QStringLiteral("combo_South"));
        combo_South->setEnabled(false);
        combo_South->setGeometry(QRect(130, 60, 51, 22));
        combo_West = new QComboBox(groupBox_4);
        combo_West->addItem(QString());
        combo_West->addItem(QString());
        combo_West->setObjectName(QStringLiteral("combo_West"));
        combo_West->setEnabled(false);
        combo_West->setGeometry(QRect(130, 90, 51, 22));
        checkBox_beacon = new QCheckBox(groupBox_4);
        checkBox_beacon->setObjectName(QStringLiteral("checkBox_beacon"));
        checkBox_beacon->setGeometry(QRect(10, 20, 61, 20));
        combo_fixdelay = new QComboBox(groupBox_4);
        combo_fixdelay->addItem(QString());
        combo_fixdelay->addItem(QString());
        combo_fixdelay->addItem(QString());
        combo_fixdelay->addItem(QString());
        combo_fixdelay->addItem(QString());
        combo_fixdelay->addItem(QString());
        combo_fixdelay->addItem(QString());
        combo_fixdelay->addItem(QString());
        combo_fixdelay->setObjectName(QStringLiteral("combo_fixdelay"));
        combo_fixdelay->setEnabled(false);
        combo_fixdelay->setGeometry(QRect(110, 20, 41, 22));
        combo_fixdelay->setEditable(true);
        label_39 = new QLabel(groupBox_4);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setEnabled(false);
        label_39->setGeometry(QRect(150, 20, 21, 20));
        groupBox_5 = new QGroupBox(Beacon);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setEnabled(false);
        groupBox_5->setGeometry(QRect(210, 10, 121, 101));
        label_3 = new QLabel(groupBox_5);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 20, 41, 16));
        label_4 = new QLabel(groupBox_5);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 40, 41, 16));
        comboHeight = new QComboBox(groupBox_5);
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->addItem(QString());
        comboHeight->setObjectName(QStringLiteral("comboHeight"));
        comboHeight->setGeometry(QRect(60, 40, 51, 16));
        label_5 = new QLabel(groupBox_5);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 60, 31, 16));
        comboGain = new QComboBox(groupBox_5);
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->addItem(QString());
        comboGain->setObjectName(QStringLiteral("comboGain"));
        comboGain->setGeometry(QRect(60, 60, 51, 16));
        label_6 = new QLabel(groupBox_5);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 80, 51, 16));
        comboDirection = new QComboBox(groupBox_5);
        comboDirection->addItem(QString());
        comboDirection->addItem(QString());
        comboDirection->addItem(QString());
        comboDirection->addItem(QString());
        comboDirection->addItem(QString());
        comboDirection->addItem(QString());
        comboDirection->addItem(QString());
        comboDirection->addItem(QString());
        comboDirection->addItem(QString());
        comboDirection->setObjectName(QStringLiteral("comboDirection"));
        comboDirection->setGeometry(QRect(60, 80, 51, 16));
        comboPower = new QComboBox(groupBox_5);
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->addItem(QString());
        comboPower->setObjectName(QStringLiteral("comboPower"));
        comboPower->setGeometry(QRect(60, 20, 51, 16));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/icons/icons/if_antenna_173140.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget->addTab(Beacon, icon10, QString());
        MainWindow->setCentralWidget(centralwidget);
        QWidget::setTabOrder(combo_ports, lineSSID);
        QWidget::setTabOrder(lineSSID, lineSymbol);
        QWidget::setTabOrder(lineSymbol, combo_symbolTable);
        QWidget::setTabOrder(combo_symbolTable, combo_path1);
        QWidget::setTabOrder(combo_path1, combo_path2);
        QWidget::setTabOrder(combo_path2, lineMessage);
        QWidget::setTabOrder(lineMessage, checkBox_course);
        QWidget::setTabOrder(checkBox_course, checkBox_beacon);
        QWidget::setTabOrder(checkBox_beacon, bnt_desconnect);
        QWidget::setTabOrder(bnt_desconnect, line_fixlat);
        QWidget::setTabOrder(line_fixlat, line_fixlon);
        QWidget::setTabOrder(line_fixlon, combo_South);
        QWidget::setTabOrder(combo_South, combo_West);
        QWidget::setTabOrder(combo_West, comboPower);
        QWidget::setTabOrder(comboPower, comboHeight);
        QWidget::setTabOrder(comboHeight, comboGain);
        QWidget::setTabOrder(comboGain, comboDirection);
        QWidget::setTabOrder(comboDirection, bnt_format);
        QWidget::setTabOrder(bnt_format, bnt_readData);
        QWidget::setTabOrder(bnt_readData, bnt_writeData);
        QWidget::setTabOrder(bnt_writeData, line_txpreamble);
        QWidget::setTabOrder(line_txpreamble, line_txtail);
        QWidget::setTabOrder(line_txtail, line_txbeep);
        QWidget::setTabOrder(line_txbeep, line_rxbeep);
        QWidget::setTabOrder(line_rxbeep, line_repbeep);
        QWidget::setTabOrder(line_repbeep, combo_cspeed);
        QWidget::setTabOrder(combo_cspeed, combo_cangle);
        QWidget::setTabOrder(combo_cangle, combo_ctime);
        QWidget::setTabOrder(combo_ctime, bnt_listPorts);
        QWidget::setTabOrder(bnt_listPorts, combo_delay1);
        QWidget::setTabOrder(combo_delay1, combo_delay2);
        QWidget::setTabOrder(combo_delay2, combo_delay3);
        QWidget::setTabOrder(combo_delay3, combo_speed1);
        QWidget::setTabOrder(combo_speed1, combo_speed2);
        QWidget::setTabOrder(combo_speed2, combo_speed3);
        QWidget::setTabOrder(combo_speed3, bnt_connect);
        QWidget::setTabOrder(bnt_connect, combo_fixdelay);

        retranslateUi(MainWindow);
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), label_10, SLOT(setEnabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), combo_fixdelay, SLOT(setEnabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), line_fixlat, SLOT(setEnabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), combo_West, SLOT(setEnabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), line_fixlon, SLOT(setEnabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), label_9, SLOT(setEnabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), groupBox_9, SLOT(setDisabled(bool)));
        QObject::connect(checkBox_course, SIGNAL(clicked(bool)), combo_cangle, SLOT(setDisabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), combo_South, SLOT(setEnabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), groupBox_5, SLOT(setEnabled(bool)));
        QObject::connect(checkBox_course, SIGNAL(clicked(bool)), combo_ctime, SLOT(setDisabled(bool)));
        QObject::connect(checkBox_course, SIGNAL(clicked(bool)), combo_cspeed, SLOT(setDisabled(bool)));
        QObject::connect(checkBox_beacon, SIGNAL(clicked(bool)), groupBox_8, SLOT(setDisabled(bool)));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "TcheTracker Configurator", nullptr));
#ifndef QT_NO_STATUSTIP
        MainWindow->setStatusTip(QString());
#endif // QT_NO_STATUSTIP
        groupBox->setTitle(QApplication::translate("MainWindow", "Serial Port", nullptr));
        bnt_listPorts->setText(QApplication::translate("MainWindow", "List Devices", nullptr));
        bnt_connect->setText(QApplication::translate("MainWindow", "Connect", nullptr));
        bnt_desconnect->setText(QApplication::translate("MainWindow", "Desonnect", nullptr));
        label_status->setText(QApplication::translate("MainWindow", "Connecting...", nullptr));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "TcheTracker", nullptr));
        bnt_format->setText(QApplication::translate("MainWindow", "Format Eeprom", nullptr));
        bnt_readData->setText(QApplication::translate("MainWindow", "Read Data", nullptr));
        bnt_writeData->setText(QApplication::translate("MainWindow", "Write Data", nullptr));
        lineMessage->setText(QApplication::translate("MainWindow", "Tcheduino/TcheTracker V8", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Symbol", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "Simblol Table", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "PATH1:", nullptr));
        combo_symbolTable->setItemText(0, QApplication::translate("MainWindow", "Normal", nullptr));
        combo_symbolTable->setItemText(1, QApplication::translate("MainWindow", "Alternate", nullptr));

        label_12->setText(QApplication::translate("MainWindow", "PATH2:", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "SSID", nullptr));
        lineSymbol->setText(QApplication::translate("MainWindow", "j", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Message:", nullptr));
        lineSSID->setInputMask(QApplication::translate("MainWindow", "NN", nullptr));
        lineSSID->setText(QApplication::translate("MainWindow", "9", nullptr));
        combo_path2->setItemText(0, QApplication::translate("MainWindow", "WIDE2-1", nullptr));
        combo_path2->setItemText(1, QApplication::translate("MainWindow", "WIDE2-2", nullptr));

        combo_path1->setItemText(0, QApplication::translate("MainWindow", "WIDE1-1", nullptr));
        combo_path1->setItemText(1, QApplication::translate("MainWindow", "WIDE1-2", nullptr));

        label->setText(QApplication::translate("MainWindow", "CallSign", nullptr));
        lineCall->setText(QApplication::translate("MainWindow", "NO1CALL", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Basic", nullptr));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "Speed Trigger Options", nullptr));
        combo_delay1->setItemText(0, QApplication::translate("MainWindow", "120", nullptr));
        combo_delay1->setItemText(1, QApplication::translate("MainWindow", "100", nullptr));
        combo_delay1->setItemText(2, QApplication::translate("MainWindow", "60", nullptr));
        combo_delay1->setItemText(3, QApplication::translate("MainWindow", "55", nullptr));
        combo_delay1->setItemText(4, QApplication::translate("MainWindow", "50", nullptr));
        combo_delay1->setItemText(5, QApplication::translate("MainWindow", "45", nullptr));
        combo_delay1->setItemText(6, QApplication::translate("MainWindow", "30", nullptr));

        combo_delay2->setItemText(0, QApplication::translate("MainWindow", "60", nullptr));
        combo_delay2->setItemText(1, QApplication::translate("MainWindow", "55", nullptr));
        combo_delay2->setItemText(2, QApplication::translate("MainWindow", "50", nullptr));
        combo_delay2->setItemText(3, QApplication::translate("MainWindow", "45", nullptr));
        combo_delay2->setItemText(4, QApplication::translate("MainWindow", "40", nullptr));
        combo_delay2->setItemText(5, QApplication::translate("MainWindow", "35", nullptr));

        combo_delay3->setItemText(0, QApplication::translate("MainWindow", "30", nullptr));
        combo_delay3->setItemText(1, QApplication::translate("MainWindow", "20", nullptr));
        combo_delay3->setItemText(2, QApplication::translate("MainWindow", "25", nullptr));
        combo_delay3->setItemText(3, QApplication::translate("MainWindow", "35", nullptr));
        combo_delay3->setItemText(4, QApplication::translate("MainWindow", "40", nullptr));
        combo_delay3->setItemText(5, QApplication::translate("MainWindow", "45", nullptr));
        combo_delay3->setItemText(6, QApplication::translate("MainWindow", "50", nullptr));
        combo_delay3->setItemText(7, QApplication::translate("MainWindow", "55", nullptr));
        combo_delay3->setItemText(8, QApplication::translate("MainWindow", "60", nullptr));

        combo_speed1->setItemText(0, QApplication::translate("MainWindow", "10", nullptr));
        combo_speed1->setItemText(1, QApplication::translate("MainWindow", "15", nullptr));
        combo_speed1->setItemText(2, QApplication::translate("MainWindow", "20", nullptr));

        combo_speed2->setItemText(0, QApplication::translate("MainWindow", "40", nullptr));
        combo_speed2->setItemText(1, QApplication::translate("MainWindow", "50", nullptr));
        combo_speed2->setItemText(2, QApplication::translate("MainWindow", "60", nullptr));
        combo_speed2->setItemText(3, QApplication::translate("MainWindow", "70", nullptr));

        combo_speed3->setItemText(0, QApplication::translate("MainWindow", "80", nullptr));
        combo_speed3->setItemText(1, QApplication::translate("MainWindow", "90", nullptr));
        combo_speed3->setItemText(2, QApplication::translate("MainWindow", "100", nullptr));

        label_27->setText(QApplication::translate("MainWindow", "1", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "2", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "3", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "(km/h)", nullptr));
        label_34->setText(QApplication::translate("MainWindow", "(km/h)", nullptr));
        label_35->setText(QApplication::translate("MainWindow", "(km/h)", nullptr));
        label_36->setText(QApplication::translate("MainWindow", "(s)", nullptr));
        label_37->setText(QApplication::translate("MainWindow", "(s)", nullptr));
        label_38->setText(QApplication::translate("MainWindow", "(s)", nullptr));
        combo_delay4->setItemText(0, QApplication::translate("MainWindow", "20", nullptr));
        combo_delay4->setItemText(1, QApplication::translate("MainWindow", "25", nullptr));
        combo_delay4->setItemText(2, QApplication::translate("MainWindow", "30", nullptr));
        combo_delay4->setItemText(3, QApplication::translate("MainWindow", "35", nullptr));
        combo_delay4->setItemText(4, QApplication::translate("MainWindow", "40", nullptr));
        combo_delay4->setItemText(5, QApplication::translate("MainWindow", "45", nullptr));
        combo_delay4->setItemText(6, QApplication::translate("MainWindow", "50", nullptr));
        combo_delay4->setItemText(7, QApplication::translate("MainWindow", "55", nullptr));
        combo_delay4->setItemText(8, QApplication::translate("MainWindow", "60", nullptr));

        label_40->setText(QApplication::translate("MainWindow", "(s)", nullptr));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "Course Trigger Options:", nullptr));
        combo_cspeed->setItemText(0, QApplication::translate("MainWindow", "15", nullptr));
        combo_cspeed->setItemText(1, QApplication::translate("MainWindow", "20", nullptr));
        combo_cspeed->setItemText(2, QApplication::translate("MainWindow", "25", nullptr));
        combo_cspeed->setItemText(3, QApplication::translate("MainWindow", "30", nullptr));
        combo_cspeed->setItemText(4, QApplication::translate("MainWindow", "35", nullptr));
        combo_cspeed->setItemText(5, QApplication::translate("MainWindow", "40", nullptr));
        combo_cspeed->setItemText(6, QApplication::translate("MainWindow", "45", nullptr));
        combo_cspeed->setItemText(7, QApplication::translate("MainWindow", "50", nullptr));
        combo_cspeed->setItemText(8, QApplication::translate("MainWindow", "55", nullptr));
        combo_cspeed->setItemText(9, QApplication::translate("MainWindow", "60", nullptr));
        combo_cspeed->setItemText(10, QApplication::translate("MainWindow", "65", nullptr));
        combo_cspeed->setItemText(11, QApplication::translate("MainWindow", "70", nullptr));
        combo_cspeed->setItemText(12, QApplication::translate("MainWindow", "75", nullptr));
        combo_cspeed->setItemText(13, QApplication::translate("MainWindow", "80", nullptr));
        combo_cspeed->setItemText(14, QApplication::translate("MainWindow", "85", nullptr));
        combo_cspeed->setItemText(15, QApplication::translate("MainWindow", "90", nullptr));

        combo_cangle->setItemText(0, QApplication::translate("MainWindow", "35", nullptr));
        combo_cangle->setItemText(1, QApplication::translate("MainWindow", "25", nullptr));
        combo_cangle->setItemText(2, QApplication::translate("MainWindow", "40", nullptr));
        combo_cangle->setItemText(3, QApplication::translate("MainWindow", "45", nullptr));
        combo_cangle->setItemText(4, QApplication::translate("MainWindow", "50", nullptr));
        combo_cangle->setItemText(5, QApplication::translate("MainWindow", "55", nullptr));
        combo_cangle->setItemText(6, QApplication::translate("MainWindow", "60", nullptr));
        combo_cangle->setItemText(7, QApplication::translate("MainWindow", "65", nullptr));
        combo_cangle->setItemText(8, QApplication::translate("MainWindow", "70", nullptr));
        combo_cangle->setItemText(9, QApplication::translate("MainWindow", "75", nullptr));
        combo_cangle->setItemText(10, QApplication::translate("MainWindow", "80", nullptr));
        combo_cangle->setItemText(11, QApplication::translate("MainWindow", "85", nullptr));
        combo_cangle->setItemText(12, QApplication::translate("MainWindow", "90", nullptr));

        label_25->setText(QApplication::translate("MainWindow", "Min time:", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "Min Angle:", nullptr));
        combo_ctime->setItemText(0, QApplication::translate("MainWindow", "15", nullptr));
        combo_ctime->setItemText(1, QApplication::translate("MainWindow", "20", nullptr));
        combo_ctime->setItemText(2, QApplication::translate("MainWindow", "25", nullptr));
        combo_ctime->setItemText(3, QApplication::translate("MainWindow", "30", nullptr));
        combo_ctime->setItemText(4, QApplication::translate("MainWindow", "35", nullptr));
        combo_ctime->setItemText(5, QApplication::translate("MainWindow", "40", nullptr));
        combo_ctime->setItemText(6, QApplication::translate("MainWindow", "45", nullptr));
        combo_ctime->setItemText(7, QApplication::translate("MainWindow", "50", nullptr));
        combo_ctime->setItemText(8, QApplication::translate("MainWindow", "55", nullptr));
        combo_ctime->setItemText(9, QApplication::translate("MainWindow", "60", nullptr));
        combo_ctime->setItemText(10, QApplication::translate("MainWindow", "65", nullptr));
        combo_ctime->setItemText(11, QApplication::translate("MainWindow", "70", nullptr));
        combo_ctime->setItemText(12, QApplication::translate("MainWindow", "75", nullptr));
        combo_ctime->setItemText(13, QApplication::translate("MainWindow", "80", nullptr));
        combo_ctime->setItemText(14, QApplication::translate("MainWindow", "85", nullptr));
        combo_ctime->setItemText(15, QApplication::translate("MainWindow", "90", nullptr));

        label_26->setText(QApplication::translate("MainWindow", "Min Speed:", nullptr));
        checkBox_course->setText(QApplication::translate("MainWindow", "Disable", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "(deg)", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "(s)", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "(km/h)", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(Smart), QApplication::translate("MainWindow", "Smart", nullptr));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "Signaling Beep", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "(ms)", nullptr));
        line_txbeep->setText(QApplication::translate("MainWindow", "1000", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "TX Beep:", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "(ms)", nullptr));
        line_rxbeep->setText(QApplication::translate("MainWindow", "500", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "RX Beep:", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "(ms)", nullptr));
        line_repbeep->setText(QApplication::translate("MainWindow", "2000", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "Repeted beep:", nullptr));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Radio TX:", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "TX Preamble:", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "TX Tail:", nullptr));
        line_txpreamble->setText(QApplication::translate("MainWindow", "450", nullptr));
        line_txtail->setText(QApplication::translate("MainWindow", "50", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "(ms)", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "(ms)", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(Radio), QApplication::translate("MainWindow", "Radio", nullptr));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Fixed Beacon (NO GPS)", nullptr));
        line_fixlat->setInputMask(QApplication::translate("MainWindow", "9999.99", nullptr));
        line_fixlat->setText(QApplication::translate("MainWindow", "0000.00", nullptr));
        line_fixlon->setInputMask(QApplication::translate("MainWindow", "99999.99", nullptr));
        line_fixlon->setText(QApplication::translate("MainWindow", "00000.00", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Latitude:", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Longitude:", nullptr));
        combo_South->setItemText(0, QApplication::translate("MainWindow", "South", nullptr));
        combo_South->setItemText(1, QApplication::translate("MainWindow", "North", nullptr));

        combo_West->setItemText(0, QApplication::translate("MainWindow", "West", nullptr));
        combo_West->setItemText(1, QApplication::translate("MainWindow", "East", nullptr));

        checkBox_beacon->setText(QApplication::translate("MainWindow", "Enable", nullptr));
        combo_fixdelay->setItemText(0, QApplication::translate("MainWindow", "60", nullptr));
        combo_fixdelay->setItemText(1, QApplication::translate("MainWindow", "120", nullptr));
        combo_fixdelay->setItemText(2, QApplication::translate("MainWindow", "180", nullptr));
        combo_fixdelay->setItemText(3, QApplication::translate("MainWindow", "240", nullptr));
        combo_fixdelay->setItemText(4, QApplication::translate("MainWindow", "300", nullptr));
        combo_fixdelay->setItemText(5, QApplication::translate("MainWindow", "360", nullptr));
        combo_fixdelay->setItemText(6, QApplication::translate("MainWindow", "420", nullptr));
        combo_fixdelay->setItemText(7, QApplication::translate("MainWindow", "480", nullptr));

        label_39->setText(QApplication::translate("MainWindow", "(s)", nullptr));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "PHGD", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Power:", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Height:", nullptr));
        comboHeight->setItemText(0, QApplication::translate("MainWindow", "10", nullptr));
        comboHeight->setItemText(1, QApplication::translate("MainWindow", "20", nullptr));
        comboHeight->setItemText(2, QApplication::translate("MainWindow", "40", nullptr));
        comboHeight->setItemText(3, QApplication::translate("MainWindow", "30", nullptr));
        comboHeight->setItemText(4, QApplication::translate("MainWindow", "80", nullptr));
        comboHeight->setItemText(5, QApplication::translate("MainWindow", "160", nullptr));
        comboHeight->setItemText(6, QApplication::translate("MainWindow", "320", nullptr));
        comboHeight->setItemText(7, QApplication::translate("MainWindow", "640", nullptr));
        comboHeight->setItemText(8, QApplication::translate("MainWindow", "1280", nullptr));
        comboHeight->setItemText(9, QApplication::translate("MainWindow", "2560", nullptr));
        comboHeight->setItemText(10, QApplication::translate("MainWindow", "5120", nullptr));

        label_5->setText(QApplication::translate("MainWindow", "Gain:", nullptr));
        comboGain->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        comboGain->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));
        comboGain->setItemText(2, QApplication::translate("MainWindow", "2", nullptr));
        comboGain->setItemText(3, QApplication::translate("MainWindow", "3", nullptr));
        comboGain->setItemText(4, QApplication::translate("MainWindow", "4", nullptr));
        comboGain->setItemText(5, QApplication::translate("MainWindow", "5", nullptr));
        comboGain->setItemText(6, QApplication::translate("MainWindow", "6", nullptr));
        comboGain->setItemText(7, QApplication::translate("MainWindow", "7", nullptr));
        comboGain->setItemText(8, QApplication::translate("MainWindow", "8", nullptr));
        comboGain->setItemText(9, QApplication::translate("MainWindow", "9", nullptr));

        label_6->setText(QApplication::translate("MainWindow", "Direction:", nullptr));
        comboDirection->setItemText(0, QApplication::translate("MainWindow", "Omni", nullptr));
        comboDirection->setItemText(1, QApplication::translate("MainWindow", "45 NE", nullptr));
        comboDirection->setItemText(2, QApplication::translate("MainWindow", "90 E", nullptr));
        comboDirection->setItemText(3, QApplication::translate("MainWindow", "135 SE", nullptr));
        comboDirection->setItemText(4, QApplication::translate("MainWindow", "180 S", nullptr));
        comboDirection->setItemText(5, QApplication::translate("MainWindow", "225 SW", nullptr));
        comboDirection->setItemText(6, QApplication::translate("MainWindow", "270 W", nullptr));
        comboDirection->setItemText(7, QApplication::translate("MainWindow", "315 NW", nullptr));
        comboDirection->setItemText(8, QApplication::translate("MainWindow", "360 N", nullptr));

        comboPower->setItemText(0, QApplication::translate("MainWindow", "0", nullptr));
        comboPower->setItemText(1, QApplication::translate("MainWindow", "1", nullptr));
        comboPower->setItemText(2, QApplication::translate("MainWindow", "2", nullptr));
        comboPower->setItemText(3, QApplication::translate("MainWindow", "4", nullptr));
        comboPower->setItemText(4, QApplication::translate("MainWindow", "9", nullptr));
        comboPower->setItemText(5, QApplication::translate("MainWindow", "16", nullptr));
        comboPower->setItemText(6, QApplication::translate("MainWindow", "25", nullptr));
        comboPower->setItemText(7, QApplication::translate("MainWindow", "36", nullptr));
        comboPower->setItemText(8, QApplication::translate("MainWindow", "49", nullptr));
        comboPower->setItemText(9, QApplication::translate("MainWindow", "64", nullptr));
        comboPower->setItemText(10, QApplication::translate("MainWindow", "81", nullptr));

        tabWidget->setTabText(tabWidget->indexOf(Beacon), QApplication::translate("MainWindow", "Beacon", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
